name: deploy the backend
on: 
  push: 
    branches: [ main ]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
          uses: actions/checkout@v2

        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: build and push
          uses: build-push-actions@v2
          with: 
            context: .
            file: ./docker/Dockerfile.backend
            push: true
            tags: dakshydv/todo-backend:${{ github.sha }}